Upgraded to Angular 16.
HyperviewHQ/angular2gridster pull request #7
Opened 2023-06-29 04:38 UTC by cklogs

LINTING:

![image](https://github.com/HyperviewHQ/angular2gridster/assets/10749074/d9c762bc-f17c-4eca-8591-df4d78b29f44)

BUILD RESULT:

![image](https://github.com/HyperviewHQ/angular2gridster/assets/10749074/9c8906cb-2f73-4a9b-b544-1cb8243c67e7)

DEPCHECK:

![image](https://github.com/HyperviewHQ/angular2gridster/assets/10749074/9877a8a4-f852-4d8f-803f-8eca583c07fd)

2023-06-29 13:27 UTC, tfadler approved these changes

2023-06-29 18:55 UTC, ramijebara requested changes
Please update the version number in package.json.

2023-06-30 02:40 UTC, cklogs commented
@ramijebara 

Bumped the version number to 16.0.0 sir.

2023-06-30 02:41 UTC, ramijebara approved these changes

2023-06-30 02:46 UTC, merged